webtalk_init -webtalk_dir D:/Logic_Design_Lab/Lab_3/Advance/Lab3_studentID_Ping_Pong_Counter/Lab3_studentID_Ping_Pong_Counter.sim/sim_1/behav/xsim/xsim.dir/Lab3_111060013_Ping_Pong_Counter_t_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 19 21:11:37 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "68e35771-2f66-4eb5-b85b-067669df4b97" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3d290744fedc4d77a53a99ca0d319bd7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "3" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "69 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "3 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "32" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.41_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "56352_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2749100731 -regid "" -xml D:/Logic_Design_Lab/Lab_3/Advance/Lab3_studentID_Ping_Pong_Counter/Lab3_studentID_Ping_Pong_Counter.sim/sim_1/behav/xsim/xsim.dir/Lab3_111060013_Ping_Pong_Counter_t_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Logic_Design_Lab/Lab_3/Advance/Lab3_studentID_Ping_Pong_Counter/Lab3_studentID_Ping_Pong_Counter.sim/sim_1/behav/xsim/xsim.dir/Lab3_111060013_Ping_Pong_Counter_t_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Logic_Design_Lab/Lab_3/Advance/Lab3_studentID_Ping_Pong_Counter/Lab3_studentID_Ping_Pong_Counter.sim/sim_1/behav/xsim/xsim.dir/Lab3_111060013_Ping_Pong_Counter_t_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
